updated JL MD
Cambridge-ICCS/summer-school-scientific-vis pull request #22
Opened 2024-07-01 15:23 UTC by j-emberton

Fleshed out Jupyter notebook comments

2024-07-01 16:22 UTC, jatkinson1000 requested changes
Thanks @j-emberton 

This generally feels sensible, but please could you remove the rogue `.DS_Store` and clean the notebook before checking in.

If we both check in clean notebooks that will help us avoid merge conflicts when working on it asynchronously

2024-07-01 16:22 UTC, jatkinson1000 commented on presentation/images/.DS_Store
Can we get rid of this `.DS_Store`?

2024-07-01 16:22 UTC, jatkinson1000 commented on notebook/Scientific_Visualisation.ipynb
This looks like it has all of the output from running the cells creating a very large diff.
Please could you do `Kernel -> Restart Kernel and Clear Outputs of All Cells` and then save and check in that version of the notebook please?

2024-07-01 17:41 UTC, j-emberton commented
should all be done

2024-07-02 09:13 UTC, jatkinson1000 approved these changes
Thanks for addressing that @j-emberton 
This looks good to me now so I will merge shortly.

2024-07-02 09:16 UTC, merged